name: CodeCov
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - ".clusterfuzzlite/hypothesis_structured_fuzzer.py"
      
      

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: ‘2’

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Generate Report
      run: |
        pip3 install coverage
        coverage run -m unittest
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
          token: ${{secrets.Codecov_Token}}
